sudo: required

services:
  - docker

before_install:
  - docker build -t aakashraina/frontend-production-workflow -f Dockerfile.dev .

script:
  - docker run aakashraina/frontend-production-workflow npm run test -- --coverage
