language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t aakashraina/frontend-production-workflow -f Dockerfile.dev .

script:
  - docker run -e CI=true aakashraina/frontend-production-workflow npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "frontend-production-workflow"
  env: "Frontendproductionworkflow-env"
  bucket_name: "elasticbeanstalk-us-east-2-813307445915"
  bucket_path: "frontend-production-workflow"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
